/* eslint-disable react/function-component-definition */
import React from 'react'
import { calculatorContainer, numberContainer, borderContainer } from './Calculator.module.css'
import Button from '../../components/Button/Button'
import Screen from '../../components/Screen/Screen'

const Calculator = () => (
  <div className={calculatorContainer}>
    <div className={borderContainer}>
      <Screen numberInput="1" numberOutput="2" />
      <div className={numberContainer}>
        <Button
          character="C"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="red"
          fontSize="30px"
        />
        <Button
          character="+/-"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <Button
          character="%"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <Button
          character="÷"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <Button
          character="7"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="8"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="9"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="X"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <Button
          character="4"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="5"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="6"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="-"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <Button
          character="1"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="2"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="3"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="+"
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#52cfc2"
          fontSize="30px"
        />
        <div style={{ gridColumn: 'span 2' }}>
          <Button
            character="0"
            borderRadius="25px"
            width="140px"
            height="65px"
            color="#b79472"
            fontSize="30px"
          />
        </div>
        <Button
          character="."
          borderRadius="75px"
          width="65px"
          height="65px"
          color="#b79472"
          fontSize="30px"
        />
        <Button
          character="="
          borderRadius="75px"
          width="65px"
          height="65px"
          color="white"
          fontSize="30px"
          backgroundColor="#52cfc2"
        />
      </div>
    </div>
  </div>
)

export default Calculator
